version: 2.1
orbs: # packages
  node: circleci/node@5.0.1
  docker: circleci/docker@2.1.4 # allows us to use docker orb's commands
  # heroku: circleci/heroku@2.0.0
jobs: # instructions for each step
  build: # Build the application, ie install dependencies
    docker: # container to handle to steps
      - image: cimg/node:16.10
    steps:
      - checkout # copies the working directory of th project
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Installing dependencies..."
          npm install
    when:
      - branch: main
  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Running tests..."
          npm run test
    when:
      - branch: main
  build-and-push:
    executor: docker/docker # State the environment that we're using
    steps:
      - setup_remote_docker #This allows use to run docker commands just in case
      - checkout
      - docker/check
      - docker/build:
          image: norulehapizah/education-space
          tag: 1.0.1
      - docker/push:
          image: norulehapizah/education-space
          tag: 1.0.1
    #   - run:
    #     name: Build and Push Docker Image
    #     command: |
    #       docker build -t norulehapizah/education-space:${CIRCLECI_PARAMETER_version} .
    #       docker oush norulehapizah/ediction-space:${CIRCLECI_PARAMETER_version}
    # when:
    #   tags:
    #     only: /^v\d+\.\d+\.\d+$/

  # deploy:
  #   docker:
  #     - image: cimg/node:16.10
  #   steps:
  #     - setup_remote_docker
  #     - heroku/install #installs heroku cli for our run command
  #     - checkout
  #     - run:
  #         name: Heroku Container Push # the name of the group of commands we are running
  #         command: |
  #           heroku container:login
  #           heroku container:push web -a nurulhafizah-su-devops
  #           heroku container:release web -a nurulhafizah-su-devops
  #       # The push command pushes the image to heroku's container registry
  #       # The release command deploys the image from heroku's container registry

workflows: # defines how each job would run and relate to each other and any other dependent states (eg: only run if pushed to main branch)
  # version: 2
  simple_workflow:
    jobs:
      - build:
          filters:
            branches:
              only: main
      - test:
          requires:
            - build
          filters:
            branches:
              only: main
      - build-and-push:
          requires:
            - test
          # filters:
          #   tags:
          #     only: /^v\d+\.\d+\.\d+$/
      # - deploy:
      #     requires:
      #       - build-and-push
